spring:
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/xzg-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 开启空闲检测
      validation-query: select 1
      stat-view-servlet:
        allow: 127.0.0.1
        login-username: happain
        login-password: happain
        # 是否能重置数据
        reset-enable: true

  #redis配置
  redis:
    password: 123456
    database: 1
    host: 127.0.0.1
    port: 6379
    #配置连接池
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

# 日志配置
logging:
  charset:
    console: utf-8
    file: utf-8
  level:
    # 默认的是info
    root: info
    # 自定义设置
    cn:
      happain:
        modules:
          userModule: info
  file:
    path: D:\my_project\xzg-springboot-cli\log



# mybait-plus配置
mybatis-plus:
  configuration:
    # 全映射
    auto-mapping-behavior: full
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath:/mapper/**/*.xml
  # 默认执行器
  executor-type: simple
  # 全局配置
  global-config:
    # 开启原生sql
    enable-sql-runner: true
    db-config:
      # auto为自增  ASSIGN_ID为雪花算法
      id-type: auto
      # 已经删除逻辑值
      logic-delete-value: 1
      logic-not-delete-value: 0





