server:
  port: 9000
  servlet:
    context-path: /
spring:
  application:
    name: modules-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xzg-admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
#        deny: 0.0.0.0
        allow: 127.0.0.1
        login-username: happain
        login-password: happain
        # 是否能重置数据
        reset-enable: true






# mybait-plus配置
#mybatis-plus:
